import type { Metadata } from "next";
import "./globals.css";
import { IM_Fell_English_SC,IM_Fell_DW_Pica } from "next/font/google";

const im_fell = IM_Fell_English_SC({
  weight: [ "400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-im",
})

const im_fell_italic = IM_Fell_DW_Pica({
  weight: [ "400"],
  style: ["italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-im-italic",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${im_fell.className} ${im_fell_italic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
